# general settings
name: train_FTVSR_BraTS_t2_x2_t15_norm
model_type: VideoRecurrentModel2
scale: 2
num_gpu: 1  # official: 8 GPUs
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: BraTS_t2_x2
    type: VideoNpyRecurrentDataset
    dataroot_gt: /mnt/zlz/Dataset/BraTS18/BraTS_HR/t2/train_slice_video
    dataroot_lq: /mnt/zlz/Dataset/BraTS18/BraTS_LR/bicubic_2x/t2/train_slice_video/
    meta_info_file: basicsr/data/meta_info/meta_info_BraTS18_train_GT.txt
    test_mode: False
    io_backend:
      type: disk
    max: 1.0
    num_frame: 15
    gt_size: 160
    interval_list: [1]
    random_reverse: false
    use_hflip: false
    use_rot: false
    #TODO 暂时关闭
    # data loader
    num_worker_per_gpu: 3
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: BraTS_t2_x2_test
    type: VideoNPYRecurrentTestDataset
    dataroot_gt: /mnt/zlz/Dataset/BraTS18/BraTS_HR/t2/test_slice_video_split_2
    dataroot_lq: /mnt/zlz/Dataset/BraTS18/BraTS_LR/bicubic_2x/t2/test_slice_video_split_2
    meta_info_file: basicsr/data/meta_info/meta_info_BraTS18_test_split2_GT.txt
    cache_data: true
    io_backend:
      type: disk
    max: 1.0
    num_frame: -1  # not needed
    padding: reflection # TODO需要修改
# network structures
network_g:
  type: FTVSRIXIx2
  mid_channels: 64
  num_blocks: 60
  stride: 4
  keyframe_stride: 3
  #dct_kernel: (8,8)
  d_model: 512
  n_heads: 8
  spynet_pretrained: ~ #experiments/pretrained_models/flownet/spynet_sintel_final-3d2a1287.pth

# path
path:
  pretrain_network_g: experiments/train_FTVSR_IXIT2_x2_t15_norm/models/net_g_50000.pth
  strict_load_g: false
  resume_state: experiments/train_FTVSR_BraTS_flair_x2_t15_norm/training_states/35000.state

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 9e-5
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [600000]
    restart_weights: [1]
    eta_min: !!float 1e-7

  total_iter: 600000
  warmup_iter: -1  # no warm up
  fix_flow: 0
  flow_lr_mul: 0.25

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: mean
  perceptual_opt:
    type: SSIMLoss
    loss_weight: 5.0
    reduction: mean


# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr_pt_2
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim_pt_py
      crop_border: 0
      test_y_channel: false
# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: true
