# general settings
name: train_BasicVSRSS4MSR_IXIT2_x2_norm_new
model_type: VideoRecurrentModel2
scale: 2
num_gpu: 1  # official: 8 GPUs
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: IXI_T2_X2
    type: VideoNpyRecurrentDataset
    dataroot_gt: ~/Datasets/IXI/IXI_HR/T2/train_slice_video_norm
    dataroot_lq: ~/Datasets/IXI/IXI_LR/bicubic_2x/T2/train_slice_video_norm
    meta_info_file: basicsr/data/meta_info/meta_info_IXIT2train_GT.txt
    test_mode: False
    io_backend:
      type: disk
    max: 1.0
    num_frame: 31
    gt_size: 128
    interval_list: [1]
    random_reverse: false
    use_hflip: false
    use_rot: false
    #TODO 暂时关闭
    # data loader
    num_worker_per_gpu: 6
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: IXI_T2_X2_test
    type: VideoNPYRecurrentTestDataset
    dataroot_gt: ~/Datasets/IXI/IXI_HR/T2/test_slice_video_norm
    dataroot_lq: ~/Datasets/IXI/IXI_LR/bicubic_2x/T2/test_slice_video_norm
    meta_info_file: basicsr/data/meta_info/meta_info_IXIT2test_GT.txt
    cache_data: true
    io_backend:
      type: disk
    max: 1.0
    num_frame: -1  # not needed
    padding: reflection # TODO需要修改
# network structures
network_g:
  type: BasicVSRSubSubX2
  mid_channels: 64
  num_blocks: 7
  is_low_res_input: true
  spynet_path: ~ #experiments/pretrained_models/flownet/spynet_sintel_final-3d2a1287.pth

# path
path:
  pretrain_network_g: experiments/train_BasicVSRSS4MSR_IXIT2_x2_norm/models/net_g_215000.pth
  strict_load_g: false
  resume_state: ~
# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 9e-5
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [600000]
    restart_weights: [1]
    eta_min: !!float 1e-7

  total_iter: 600000
  warmup_iter: -1  # no warm up
  fix_flow: 0
  flow_lr_mul: 0.25

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr_pt_2
      crop_border: 0
      test_y_channel: false
# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: true
