# general settings
name: train_ShiftViT_SRx4_scratch_P48W8_DIV2K_500k_B4G8
model_type: ShiftViTModel
scale: 4
num_gpu: auto
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: DIV2K
    type: PairedImageDataset
    dataroot_gt: ~/Datasets/DIV2K/DIV2K_train_HR
    dataroot_lq: ~/Datasets/DIV2K/DIV2K_train_LR_bicubic/X4
    filename_tmpl: '{}x4'
    io_backend:
      type: disk

    gt_size: 192
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 1
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: DIV2K_test
    type: PairedImageDataset
    dataroot_gt: ~/Datasets/DIV2K/DIV2K_valid_HR
    dataroot_lq: ~/Datasets/DIV2K/DIV2K_valid_LR_bicubic/X4
    filename_tmpl: '{}'
    io_backend:
      type: disk

# network structures
network_g:
  type: ShiftViT
  upscale: 4
  #in_chans: 3
  img_size: 48
  img_range: 1.
  depths: [10,18,35,10]
  embed_dim: 128
  num_heads: [10,18,35,10]
  mlp_ratio: 2
  upsampler: 'pixelshuffledirect'

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: experiments/train_ShiftViT_SRx4_scratch_P48W8_DIV2K_500k_B4G8/training_states/290000.state

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [250000, 400000, 450000, 475000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false
  pbar: true
  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
