# general settings
name: train_HAN_SRx3_IXI_T2
model_type: SRModel
scale: 3
num_gpu: auto
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: IXI_T2_X3
    type: PairedNpyDataset
    dataroot_gt: ~/Datasets/IXI/IXI_HR/T2/train_slice/
    dataroot_lq: ~/Datasets/IXI/IXI_LR/bicubic_3x/T2/train_slice
    filename_tmpl: '{}'
    io_backend:
      type: disk
    max: 1.0
    gt_size: 192
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 4
    batch_size_per_gpu: 3
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: IXI_T2_X3_test
    type: PairedNpyDataset
    max: 1.0
    dataroot_gt: ~/Datasets/IXI/IXI_HR/T2/test_slice
    dataroot_lq: ~/Datasets/IXI/IXI_LR/bicubic_3x/T2/test_slice
    io_backend:
      type: disk

# network structures
network_g:
  type: HAN
  scale: 3


# path
path:
  pretrain_network_g: experiments/train_HAN_SRx4_IXI_T2/models/net_g_110000.pth
  strict_load_g: false
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [250000, 400000, 450000, 475000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false
  pbar: true
  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false
# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
